[project]
name = "zak"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.4.1",
    "openai>=2.32.0",
    "pyfiglet>=1.0.4",
    "python-dotenv>=1.2.2",
    "questionary",
    "requests>=2.33.1",
    "rich>=15.0.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "ruff>=0.15.15",
]
